// Generated by CoffeeScript 1.3.3
(function() {

  window.addEvent('domready', function() {
    var input, _i, _len, _ref;
    _ref = $$('.fancyCheckbox');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      new FancyBox(input);
    }
    new SexyScroll($('longContent'));
    return true;
  });

}).call(this);
